openapi: "3.0.0"
info:
  title: Food Delivery API
  description: API documentation for the Food Delivery application
  version: "1.0.0"
servers:
  - url: "http://localhost:3000"
paths:
  /api/pricing:
    post:
      summary: Calculate price for food delivery
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                zone:
                  type: string
                organization_id:
                  type: string
                total_distance:
                  type: number
                item_type:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
        '400':
          description: Invalid request
        '500':
          description: Internal server error
